// autoloan-nextjs-metafullstack/src/app/layout.test.tsx
import { describe, it, expect, vi } from 'vitest';
import { render, screen } from '@testing-library/react';

vi.mock('next/font/google', () => ({
  Geist: () => ({ variable: '--font-geist-sans' }),
  Geist_Mono: () => ({ variable: '--font-geist-mono' }),
}));

import RootLayout from './layout';

describe('RootLayout', () => {
  it('renders children content', () => {
    render(
      <RootLayout>
        <div data-testid="child">Test Content</div>
      </RootLayout>
    );
    expect(screen.getByTestId('child')).toBeInTheDocument();
    expect(screen.getByText('Test Content')).toBeInTheDocument();
  });

  it('exports metadata with title and description', async () => {
    const layoutModule = await import('./layout');
    const metadata = (layoutModule as Record<string, unknown>).metadata as {
      title: string;
      description: string;
    };
    expect(metadata).toBeDefined();
    expect(metadata.title).toBe('Create Next App');
    expect(metadata.description).toBe('Generated by create next app');
  });

  it('renders as a function component', () => {
    expect(typeof RootLayout).toBe('function');
  });
});
